import { bootstrapApplication } from '@angular/platform-browser';
import { provideFirebaseApp, initializeApp } from '@angular/fire/app';
import { provideAuth, getAuth } from '@angular/fire/auth';
import { provideFirestore, getFirestore } from '@angular/fire/firestore';
import { addIcons } from 'ionicons';
import {
  add,
  addCircleOutline,
  addOutline,
  arrowDown,
  arrowDownOutline,
  arrowUp,
  arrowUpOutline,
  barChartOutline,
  calendarOutline,
  cashOutline,
  chatboxOutline,
  checkboxOutline,
  checkmarkCircleOutline,
  createOutline,
  documentsOutline,
  documentTextOutline,
  fileTrayStackedOutline,
  folderOpenOutline,
  gridOutline,
  home,
  homeOutline,
  informationCircleOutline,
  keyOutline,
  libraryOutline,
  listOutline,
  logOutOutline,
  mailOutline,
  menu,
  notificationsOutline,
  pencilOutline,
  person,
  personAdd,
  personOutline,
  playCircle,
  pricetagOutline,
  radio,
  readerOutline,
  remove,
  search,
  statsChartOutline,
  swapHorizontal,
  timeOutline,
  trash,
  trashOutline,
  trendingUp,
  wallet,
  walletOutline,
} from 'ionicons/icons';
import {
  RouteReuseStrategy,
  provideRouter,
  withPreloading,
  PreloadAllModules,
} from '@angular/router';
import {
  IonicRouteStrategy,
  provideIonicAngular,
} from '@ionic/angular/standalone';

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';
import { environment } from './environments/environment';

// Register commonly used icons globally
addIcons({
  menu,
  calendarOutline,
  documentsOutline,
  documentTextOutline,
  fileTrayStackedOutline,
  informationCircleOutline,
  home,
  radio,
  libraryOutline,
  search,
  addOutline,
  playCircle,
  trash,
  homeOutline,
  listOutline,
  personOutline,
  logOutOutline,
  cashOutline,
  createOutline,
  statsChartOutline,
  readerOutline,
  gridOutline,
  wallet,
  checkmarkCircleOutline,
  personAdd,
  arrowDown,
  arrowUp,
  add,
  remove,
  swapHorizontal,
  arrowUpOutline,
  arrowDownOutline,
  trendingUp,
  folderOpenOutline,
  trashOutline,
  addCircleOutline,
  barChartOutline,
  timeOutline,
  keyOutline,
  mailOutline,
  person,
  pencilOutline,
  notificationsOutline,
  pricetagOutline,
  walletOutline,
  chatboxOutline,
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
    provideFirebaseApp(() => initializeApp(environment.firebase)),
    provideAuth(() => getAuth()),
    provideFirestore(() => getFirestore()),
  ],
});
